apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: tf-sa-dev-us-central1 # {"$kpt-set":"service-account-name"}
  namespace: YOUR_NAMESPACE # {"$kpt-set":"namespace"}
spec:
  displayName: Cluster Service Account for dev-us-central1 # {"$kpt-set":"service-account-display-name"}
